# R2DBC (Reactive Database Config)

spring.r2dbc.url=r2dbc:mariadb://localhost:3306/flightdb?allowPublicKeyRetrieval=true&useSSL=false
spring.r2dbc.username=root
spring.r2dbc.password=20080001


# Optional -for debugging R2DBC queries
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.mariadb=DEBUG


# Server
server.port=8080

# Spring Logging
logging.level.root=INFO
logging.level.com.flight=DEBUG
