spring.application.name=MnimalFlightBookingWebFlux
server.port=8080


spring.r2dbc.url=r2dbc:h2:file:///./flightdb
spring.r2dbc.username=
spring.r2dbc.password=


logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.io.r2dbc.h2=DEBUG